### ISSUE TITLE
Zipper not reporting Content-Lenght

### ISSUE THREAD

**Issue by defvs** [monstercat/s3-zipper#3]
See Pull request #2

**Comment by defvs** [comment]
As said in the PR #2 ; It is impossible with `archive.pipe` to get file size; It could be possible but the zip file must be stored before sent. (see [https://github.com/archiverjs/node-zip-stream/issues/18](https://github.com/archiverjs/node-zip-stream/issues/18) )
My suggestion : Storing, determining size, sending it, and invalidating link an hour later / allow only an ip

**Comment by tmathews** [comment]
I'm going to close this because we will not support this at any time. There should be tools to script mass downloaders, etc.
